// <auto-generated />
using System;
using AiKnowledgeAssistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiKnowledgeAssistant.Api.Migrations
{
    [DbContext(typeof(JobExecutionDbContext))]
    partial class JobExecutionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiKnowledgeAssistant.Infrastructure.Persistence.Entities.JobExecutionEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("job_id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("executed_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("workflow_id");

                    b.HasKey("JobId");

                    b.HasIndex("WorkflowId", "Environment", "ExecutedAt");

                    b.HasIndex("WorkflowId", "Environment", "Status", "ExecutedAt");

                    b.ToTable("job_executions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
